### ISSUE TITLE
After speed ~140 the silicone bands "expand". Do I use glue? 

### ISSUE THREAD

**Issue by vmartrix** [xeonqq/SpeedyBirdie#10]
Hello!
I've tried to use 2 different kinds of silicone band on the throwing wheel, but after around speed 140 set on the main page the silicone bands expand and start to damage the birdie slide platform and it doesn't throw the birdie properly anymore. 
I don't remember with the thinner bands the problem was around the same speedy, but even with the [wider ones](https://www.aliexpress.com/item/1005005865378435.html) the problem keeps happenning.
Did you glue yours to the wheel?
Or is my speed way to high and/or my motors are uncalibrated?

**Comment by xeonqq** [comment]
Yes, I face the same problem. I use epoxy to glue the rubber bands. But after extensive usage in high speed, even with glue it can still fall out. I have a slightly improved version of the spinning wheel in [ver2](https://github.com/xeonqq/SpeedyBirdie#sponsor-content). But it is still experimental since I didn't test it enough.
I am open with better ideas to fix the rubber bands.🙂

**Comment by hurrricane478** [comment]
How about 3D printer timing belts? They often have metal wire in them to prevent stretching.

**Comment by vmartrix** [comment]
> How about 3D printer timing belts? They often have metal wire in them to prevent stretching.

What do you mean by timing belts?

**Comment by vmartrix** [comment]
> Yes, I face the same problem. I use epoxy to glue the rubber bands. But after extensive usage in high speed, even with glue it can still fall out. I have a slightly improved version of the spinning wheel in [ver2](https://github.com/xeonqq/SpeedyBirdie#sponsor-content). But it is still experimental since I didn't test it enough. I am open with better ideas to fix the rubber bands.🙂

The only other option that I saw was to use a small rubber tire, for a RC truck or something like that. But it was on a different wheel design

Do you thing that hot glue would fly away due to centrifugal force as well?

**Comment by hurrricane478** [comment]
> > How about 3D printer timing belts? They often have metal wire in them to prevent stretching.
> 
> What do you mean by timing belts?

[These](https://www.google.com/search?safe=active&client=ms-android-huawei-rev1&sca_esv=557478435&sxsrf=AB5stBhcczPQMagIVUuIWVoe7p5E_Oh_Iw:1692199712115&q=3d+printer+timing+belt&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjU3OqVv-GAAxW1QEEAHV3lAvEQ0pQJegQICBAB&biw=598&bih=1140&dpr=1.81)

**Comment by vmartrix** [comment]
Oh, I didn't know they had this name. Then we'd have to design a grooved wheel, right?

**Comment by hurrricane478** [comment]
Possibly, although maybe the toothed part could face outwards, it may grip okay. I just thought of them because they have a metal core to stop them expanding over time.

**Comment by vmartrix** [comment]
Ah, okay. So the problem comes back to how to attach it to the existing wheel. The silicone armband suits nice because its elastic force grips nicely to the wheel, but it loosens when too fast. The grip to the outside is okay, the problem is the grip to the wheel or how to "glue" it better

**Comment by hurrricane478** [comment]
Yeah, maybe it would be most beneficial to have the teeth inward to gain stability, and at that point new wheels will be needed.

**Comment by xeonqq** [comment]
Close, since the question is answered. 
Feel free to keep brainstorming in this thread.
