### ISSUE TITLE
Can not flash bin file

### ISSUE THREAD

**Issue by KinInEngland** [xeonqq/SpeedyBirdie#11]
I flashed firmware successfully with flash download tool 3.9.2.But the problem is i can not find the wifi signal named "SpeedyBirdie".I do a little research that there is two kind of esp8266.nodemcu v1.0 from Amica and nodemcu v3 from other group.I can not figure out the problem.Best wish.
I can not upload the picture or video so i describe to you . The sofeware displayed "finish". The board blue led flash glimmered rapidly.

**Comment by KinInEngland** [comment]
https://github.com/xeonqq/SpeedyBirdie/assets/142132789/5bb86d88-721e-4cdc-bc28-8dd7c99600e9

**Comment by KinInEngland** [comment]
![flash_success(1)](https://github.com/xeonqq/SpeedyBirdie/assets/142132789/5f50164c-a223-44c6-aef1-d2655c09e53a)

**Comment by xeonqq** [comment]
Hi, could you try spi mode DIO, as documented [here](https://payhip.com/b/kO4ir) in the picture.

**Comment by KinInEngland** [comment]
the same problem.i don't know why.

**Comment by KinInEngland** [comment]
![image](https://github.com/xeonqq/SpeedyBirdie/assets/142132789/d0fccaf3-5e7a-4fd6-a522-e1e3274e816e)

**Comment by xeonqq** [comment]
Then I also don't know, maybe try method 2?

**Comment by xeonqq** [comment]
Btw, don't forget to power cycle the board after flashing.

**Comment by KinInEngland** [comment]
https://github.com/xeonqq/SpeedyBirdie/assets/142132789/988efa23-cf42-42df-ae00-b8527bf8303b

finally，the problem is the version of the board .btw the software seem to have little problem.

**Comment by KinInEngland** [comment]
i cannot change the number like the shooting power.

**Comment by xeonqq** [comment]
Could you describe what is the version that's working and what is not working? So that future users could benefit.

Regarding the number problem, I will have a look next week, now out of home and I don't have the hardware.

**Comment by helloworldleung** [comment]
ok，i will do it

**Comment by helloworldleung** [comment]
what's more,could you tell me more about the size of the box and more detail like the screw pitch. I want to print a box.

**Comment by xeonqq** [comment]
See thingiverse for box dimensions. Pitch I don't know. I use the screws from [ikea](https://www.ikea.com/us/en/p/fixa-200-piece-wood-screw-set-70224228/)

**Comment by KinInEngland** [comment]
https://github.com/xeonqq/SpeedyBirdie/assets/142132789/739caa66-c011-4efe-ae06-587764c73fd9

https://github.com/xeonqq/SpeedyBirdie/assets/142132789/e6b492b4-754c-4665-a1f0-e6c7981fdbe5

**Comment by KinInEngland** [comment]
hello，i want to make sure that when i press the start feeding the icon will chang?

**Comment by KinInEngland** [comment]
i changed the mobile phone and connected the web app sucessfully.but i cannot control the moter.

**Comment by vmartrix** [comment]
> what's more,could you tell me more about the size of the box and more detail like the screw pitch. I want to print a box.

I used the same box he showed there on Thingiverse: 24 x 34 x 18cm
And I bought a bunch of nuts and screws from Amazon. Used a lot of different sizes M3 and a couple of M4

**Comment by helloworldleung** [comment]
https://github.com/xeonqq/SpeedyBirdie/assets/110042413/c867b87d-297d-4048-9c20-2f75374102b7


https://github.com/xeonqq/SpeedyBirdie/assets/110042413/d7bbc87b-3394-4e93-993a-809dfdb49a7e

**Comment by helloworldleung** [comment]
hello，i have a question that the motor will start when connect to the power?i gave the signal to the board by the phone but it seem to me than it didn't work.(i connect the pin d2 to pin 3v3 on the board)

**Comment by xeonqq** [comment]
Check your connections and you can use 192.168.0.1/dev.html to debug the motors/servos easier.

**Comment by xeonqq** [comment]
Close, it seems there is no problem with the pre-compiled bin firmware. 

Debugging user specific hardware problem is out of scope for the maintainer.
