### ISSUE TITLE
Serving time lower than 3 seconds doesn't save

### ISSUE THREAD

**Issue by vmartrix** [xeonqq/SpeedyBirdie#12]
Hello!

I've tried to set for a 2.0 serving time on the main screen, but even after clicking on Save Config, if I refresh the page, it comes back to 3 seconds.
And if I try Save Config and then Run the process, it doesn't work either.

Do you also face this issue or is it with my build?

I've used the original way of flashing the drive, with the whole docker process

**Comment by xeonqq** [comment]
it is intended behavior, due to physical limitation of the servos. Namely, the grabber and the lifter can not move simultaneously, and their motion takes time. 

see: https://github.com/xeonqq/SpeedyBirdie/blob/master/app/application.cpp#L227

you can push the limit of the servos by making them moving faster, then the interval lower bound will go lower.
have to change L11-L13: https://github.com/xeonqq/SpeedyBirdie/blob/master/app/application.cpp#L11
And recompile, there are hard-coded for now.

**Comment by vmartrix** [comment]
Ah, okay. Good to know.
Recompile means to run _make flash_ and then _make flashapp_?

And considering that you mentioned recompiling, if I were to edit the main.html to include a button to dev.html for example, do I have to just make this edit on the .html files and then do the same process? Or is there any other dependency?

**Comment by xeonqq** [comment]
```make flash``` will do a fresh install of everything onto the board (code and website)
```make flashapp``` will only upload code to the board (website will not be updated)

no other deps, just modify the html and ```make flash```, you can consider submit a PR afterwards, I think it is a good feature to have a dev.html redirect button

**Comment by KinInEngland** [comment]
https://github.com/xeonqq/SpeedyBirdie/assets/142132789/09fd9a4b-86c5-4a25-8ce7-e2f9cdd9484c

hello，it seem to me that the mechanism is ok but when i started the servo have no a action do you kow why ?

**Comment by KinInEngland** [comment]
hello，it seem to me that the mechanism is ok but when i started the servo have no action do you kow why ?

**Comment by xeonqq** [comment]
@KinInEngland I have already answered your question here https://github.com/xeonqq/SpeedyBirdie/issues/11#issuecomment-1682818255, you need to configure the setting in dev.html.

Your comments are not related to the current issue at all.

**Comment by xeonqq** [comment]
question has been answered

**Comment by xeonqq** [comment]
> Ah, okay. Good to know. Recompile means to run _make flash_ and then _make flashapp_?
> 
> And considering that you mentioned recompiling, if I were to edit the main.html to include a button to dev.html for example, do I have to just make this edit on the .html files and then do the same process? Or is there any other dependency?

I added this button to navigate to dev page in master now.
In case you re-flash, please mind the updated notes here https://github.com/xeonqq/SpeedyBirdie#flash
