### ISSUE TITLE
Cannot find build instructions

### ISSUE THREAD

**Issue by hurrricane478** [xeonqq/SpeedyBirdie#7]
Hi there, 

Sorry about posting this here, but I haven't seen you active elsewhere on YouTube or Thingiverse. Would you mind posting some instructions on the build and the wiring for this?

Thank you so much, all the best.

**Comment by xeonqq** [comment]
Hi,
Sorry, for now there is no detailed assembly instructions. I hope I can find time to do it someday. I leave this issue open as a reminder.

**Comment by hurrricane478** [comment]
Okay, thanks for the quick reply. Would you mind posting a few extra pictures of the electronics when you have the time?

**Comment by xeonqq** [comment]
Here you go:
https://github.com/xeonqq/SpeedyBirdie/tree/master#sponsor-content

**Comment by hurrricane478** [comment]
Thank you!

**Comment by vmartrix** [comment]
Sorry to jump in out of nowhere
I finished my speedy birdie assembly and I am now trying to adjust a bug on one of my ESC that keeps the motor spinning even without any instruction
@hurrricane478 I can help you with pictures of any part of it, if you want. I spent 2 days of my weekend trying to reverse engineering based on the pictures, 3d pieces and video
It's working, but I wasn't able to fully test on the badminton court

@xeonqq: your work is amazing! Thank you for all the code, 3d parts and everything. It's my first arduino project and I felt so happy when it worked. I am not a code, but I'm trying to add some additional functions, like pre-made shots (like Baddy), but it's a long term plan for me.
Count with me if I can help somehow 

![image](https://github.com/xeonqq/SpeedyBirdie/assets/25043383/d497a417-34a1-4a1b-a10a-d0289d2caf04)

**Comment by hurrricane478** [comment]
Hi @vmartrix! Good build you have there, and thanks for the offer for pictures. I was also planning to add some features, and I was mainly interested in the connection board used to distribute 5v from the ESCs to see if that would work with the extra components I was planning to add or if I needed another 5v source.

As for your ESC, I would see if you can easily switch them on the Arduino pins like if you had one ESC on pins abc and another ESC on xyz them switch the one of abc to xyz and vice versa (I don't use pin numbers here as this may cause confusion). 

If the problem persists on the same ESC I would firstly check if that one if 100% wired correctly to the motor and if it is then it is likely the ESC that's gone. This is how it sometimes with Aliexpress components. Maybe disconnect the PWM pin altogether and see if it spins only with the voltage pins. 

If it persists on the other ESC then the issue is either that it's wired to the Arduino correctly (check if the PWM cable of the motor is on a PWM pin of the Arduino) and if it is then it's likely a software or Arduino bug. If that is the case then I haven't properly studied the code so I can't help you on that yet. The Arduino forums are also a fantastic place. Worst case it is probably not drawing that much current if you keep it as is.

**Comment by vmartrix** [comment]
@hurrricane478 unfortunately that's one thing that I cannot help, as I built a workaround for that
I am using a [NodeMCU](https://www.aliexpress.com/item/1005005470719229.html). It doesn't have a 5V port, so I decided to go to a different route. The servos are connected on the board's 3V and GND and on D5 and D6.
The ESCs are connected on the D0, D1 and one of them also a GND. That last GND was the only way I got it running, without it, they beep the "I don't have a PWM signal, pls help".
The 5Vs from the ESCs are ignored, so I have to power my NodeMCU with a normal powerbank.
I used a [Y splitter](https://www.amazon.de/dp/B09TXRT791) from the lipo battery to the ESCs

I tried to build with the [Wemos D1,](https://www.aliexpress.com/item/32465811688.html) but then I would have to keep a breadboard there to distribute the 5V from the ESC to the board and to both servos. As I have a spare powerbank, but not a spare breadboard, I decided to keep the NodeMCU there for now

Regarding my ESC problem on one motor, I just used a calibration code again, for a longer time, and it's not ghost-spinning anymore. Both are running fine and idling correctly.

**Comment by hurrricane478** [comment]
Yeah, calibration was something I forgot about, good that you found that. The 2x 5V 2A from the ESCs is just enough for the amount of servos that I am driving as they won't be running at the same time for the most part. I will be using [these](https://www.aliexpress.com/item/1005003206231606.html?spm=a2g0n.shopcart.0.0.18f938daSleHVL&mp=1) for power distribution and I will keep the two ESC 5V channels separate, not in parallel.

I would be wary of powering the servos through the Arduino by the way, they can't supply much current, so I would check if your voltage step down chip is getting warm. Check the current ratings too, I only tend to use the built-in 5V and 3.3V for stuff like sensors.

**Comment by vmartrix** [comment]
Where does this voltage step down is located? On the NodeMCU? I'm connecting them directly to the board's 3V and GND
How do I check what's the amp that the servos are demanding?

**Comment by hurrricane478** [comment]
You can easily get specs by [looking up the part number of any component](https://www.google.com/search?q=mg996r+current&safe=active&client=ms-android-huawei-rev1&sca_esv=556306135&sxsrf=AB5stBh4zpKcg9y6REsyg4TW8xwHUTuGZQ%3A1691847121256&ei=0YnXZMmlD-6NhbIP0OGX6Ao&oq=mg996r+current&gs_lp=EhNtb2JpbGUtZ3dzLXdpei1zZXJwIg5tZzk5NnIgY3VycmVudDIHECMYigUYJzIEECMYJzIGEAAYFhgeMgYQABgWGB4yCBAAGIoFGIYDMggQABiKBRiGAzIFEAAYogQyBRAAGKIESMsMUNkGWMMJcAF4AZABAJgBjQGgAf4BqgEDMC4yuAEDyAEA-AEBwgIHECMYsAMYJ8ICChAAGEcY1gQYsAPiAwQYACBBiAYBkAYJ&sclient=mobile-gws-wiz-serp ) and getting current values. Using V=IR the current should be half that as it is for 6V, so a about 200mA to 450mA when moving normally (I would lean more toward the lower end of that range as they don't have much load) however if you set the grabber servo in a way that will mean it tries to squeeze the shuttle then you can easily hit the stall current for at least a brief moment of time, this would be 1.25A at 3V. I couldn't find good specs about the board's 3.3V pin but similar boards can supply only 80-250mA sustained and just maybe about 500mA peak. 

If you want to measure this yourself then you need to use a multimeter connected in series between the servo and **one** of its voltage pins. It must be in series not parallel, you may cause a shortcircuit otherwise. 

Also, these servos are designed to operate from 4.8V to 6V so I would take note of that too. This will reduce their operating speed. I will personally use the 5V from the ESCs as this gives me about as much power as I need as I will be adding 2 more steppers and a sensor to my design.

**Comment by xeonqq** [comment]
> Sorry to jump in out of nowhere I finished my speedy birdie assembly and I am now trying to adjust a bug on one of my ESC that keeps the motor spinning even without any instruction @hurrricane478 I can help you with pictures of any part of it, if you want. I spent 2 days of my weekend trying to reverse engineering based on the pictures, 3d pieces and video It's working, but I wasn't able to fully test on the badminton court
> 
> @xeonqq: your work is amazing! Thank you for all the code, 3d parts and everything. It's my first arduino project and I felt so happy when it worked. I am not a code, but I'm trying to add some additional functions, like pre-made shots (like Baddy), but it's a long term plan for me. Count with me if I can help somehow
> 
> ![image](https://user-images.githubusercontent.com/25043383/260224821-d497a417-34a1-4a1b-a10a-d0289d2caf04.png)

Very nice build!

**Comment by hurrricane478** [comment]
A bit random, how much does the machine weigh roughly? I know this can vary, I just need a rough figure. Thanks.

**Comment by xeonqq** [comment]
I am again out of home for one week, so based on my muscle memory, maybe 1.5~2kg. @vmartrix maybe you can give a more accurate number.

**Comment by vmartrix** [comment]
> > Sorry to jump in out of nowhere I finished my speedy birdie assembly and I am now trying to adjust a bug on one of my ESC that keeps the motor spinning even without any instruction @hurrricane478 I can help you with pictures of any part of it, if you want. I spent 2 days of my weekend trying to reverse engineering based on the pictures, 3d pieces and video It's working, but I wasn't able to fully test on the badminton court
> > 
> > @xeonqq: your work is amazing! Thank you for all the code, 3d parts and everything. It's my first arduino project and I felt so happy when it worked. I am not a code, but I'm trying to add some additional functions, like pre-made shots (like Baddy), but it's a long term plan for me. Count with me if I can help somehow
> > 
> > ![image](https://user-images.githubusercontent.com/25043383/260224821-d497a417-34a1-4a1b-a10a-d0289d2caf04.png)
> 
> Very nice build!

Thank you!
As a first project, it works better than I expected. You did an awesome work with the code

**Comment by vmartrix** [comment]
> A bit random, how much does the machine weigh roughly? I know this can vary, I just need a rough figure. Thanks. 

Yes, he is right.
Mine has some different components than his, but it's around 2kg
I used the same box he suggested and it's very light. I liked it. 
The main variables are the 2200mah battery and the cardboard birdie tube
![PXL_20230813_181946844.jpg](https://github.com/xeonqq/SpeedyBirdie/assets/25043383/fc0a5a3b-185a-4630-a993-009031360d4e)

**Comment by xeonqq** [comment]
@vmartrix it would be cool if you put your SpeedyBirdie picture also to https://www.thingiverse.com/thing:5827863/make, it serves as an unique central place, then I can link it on the GitHub front page for others to see.

**Comment by vmartrix** [comment]
Sure, I can do that this weekend. I printed the tripod and I am planning to design and print a new lock for my cardboard tube. But for sure I can publish it there soon

**Comment by hurrricane478** [comment]
Hi again everyone, would you guys mind doing a quick experiment for me? If you would tilt the feeder down 45° or close to that to simulate a smash and see if the shuttle comes out properly or if it misses the wheels. Thanks!

**Comment by xeonqq** [comment]
I just tried, it doesn't work like that. When tilt it  45° downwards, the slide has no effect and the ball can not get good contact with the spin wheel

**Comment by hurrricane478** [comment]
Okay, thanks for doing that. I might have an idea to fix that if you are ever interested in adding shot angle control.

**Comment by vmartrix** [comment]
That sounds nice
I would like to see the solution for that. On my tests, I didn't go as far as 45 degrees. I guess only around 20 or 30 at most

**Comment by hurrricane478** [comment]
There are two solutions, both have benefits and drawbacks, and both require serious modification to the machine.

Method 1 is to have a guard that keeps the shuttle in place and then push it in manually with a servo [like this](https://www.youtube.com/watch?v=3aRCU1ZyTPs). This requires an extra servo and cannot automatically control angle, and it places an obstruction in the shuttle's path, which may lower shuttle speed and distance. It is however quite simple.

Method 2 is to change the angle of the wheels that launch the shuttle rather than change the angle of the box, like the [Siboasi machine](https://youtu.be/-A9s2fgrcPo?si=2_rdC-GzyBdyCJuY&t=74) (apologies for the fact that the only demonstration of this that I could find being a 1 second moment at 1:13 in the video). This adds an extra servo too but this servo now adds automatic angle control too, but the mechanism will require more maths to get right. The meeting point of the shuttle and the wheels cannot move so the axis of rotation will have to be at the meeting point.

I am going with method 2 but I have not yet formally put my design into proper sketches/CAD or into the real world yet, but will update on progress. I am nearly at the building stage.
