### ISSUE TITLE
Bearing dimensions

### ISSUE THREAD

**Issue by hurrricane478** [xeonqq/SpeedyBirdie#8]
Hi again, thanks for posting those instructions, I have just got them. These will really help me get this together, and I hope my donation could pay for a nice coffee or something like that 🙂

I just wanted to quickly check one thing, one is for the bearing that is 10*4mm - does this mean 10mm outer diameter by 4mm inner diameter? Does the depth of the bearing matter?

Thanks for all your work on this, ever since [baddy](https://www.badmintoncentral.com/forums/index.php?threads/launcher-shuttlecock-baddy-cheap-open-source.172538/)  was abandoned you are the only one working on this.

**Comment by xeonqq** [comment]
Hi, thanks for supporting the project. Regarding the bearing, I will check on Tuesday when I am back home, now on holiday.
But you can verify by printing 
![image](https://github.com/xeonqq/SpeedyBirdie/assets/4160429/24cd540b-80ff-404f-b0eb-704215a7c4a7)

And 

![image](https://github.com/xeonqq/SpeedyBirdie/assets/4160429/fc2e5e69-2612-483a-b147-fde2322eac1f)
 
It is used to fit those two.

**Comment by hurrricane478** [comment]
Fantastic, will take a look.

**Comment by xeonqq** [comment]
Hi, I have updated the spec of the bearing as well as a replacement solution in the manual.pdf (Tips of Building Chapter). Check out if you can download the updated one?

**Comment by hurrricane478** [comment]
No unfortunately I can't.

**Comment by xeonqq** [comment]
Alright, I just send you via email
